"""
General finite-group exact F2 homological-algebra engine.

Parametrised by an arbitrary multiplication table (list of lists), identity index,
and a generating set. Reuses the F2 linear algebra and the resolution / Ext
machinery from the (Z/2)^r engine (rick-v8-ext/gen.py), but with group operations
driven by a table so it works for NON-ABELIAN groups (D8 in particular).

Module M = {'d': F2-dim, 'act': [ (d x d) uint8 matrix for each group basis elt ]}.
act[i] = action of the i-th group element on M over F2.
"""
import numpy as np

# ---------------- exact F2 linear algebra ----------------
def mod2(M): return np.asarray(M, dtype=np.uint8) & 1

def rref(M):
    M = mod2(M).copy(); rows, cols = M.shape; pivots = []; r = 0
    for c in range(cols):
        piv = None
        for i in range(r, rows):
            if M[i, c]: piv = i; break
        if piv is None: continue
        M[[r, piv]] = M[[piv, r]]
        for i in range(rows):
            if i != r and M[i, c]: M[i] ^= M[r]
        pivots.append(c); r += 1
        if r == rows: break
    return M, pivots

def rank(M):
    if M.size == 0: return 0
    _, p = rref(M); return len(p)

def kernel(M):
    M = mod2(M); rows, cols = M.shape
    R, pivots = rref(M); pivset = set(pivots)
    free = [c for c in range(cols) if c not in pivset]
    basis = []; piv_row = {pivots[i]: i for i in range(len(pivots))}
    for f in free:
        x = np.zeros(cols, dtype=np.uint8); x[f] = 1
        for pc in pivots:
            if R[piv_row[pc], f]: x[pc] ^= 1
        basis.append(x)
    if not basis: return np.zeros((cols, 0), dtype=np.uint8)
    return np.array(basis, dtype=np.uint8).T

def solve(A, B):
    A = mod2(A); B = mod2(B); m, n = A.shape; k = B.shape[1]
    aug = np.concatenate([A, B], axis=1); R, piv = rref(aug)
    for p in piv:
        if p >= n: raise ValueError("inconsistent system")
    X = np.zeros((n, k), dtype=np.uint8); piv_row = {piv[i]: i for i in range(len(piv))}
    for pc in piv:
        if pc < n: X[pc] = R[piv_row[pc], n:n+k]
    return X

# ---------------- general finite group ----------------
class FiniteGroup:
    def __init__(self, mul_table, ident, gens, names=None):
        self.mt = [list(row) for row in mul_table]
        self.N = len(self.mt)
        self.e = ident
        self.gen_idx = list(gens)
        self.names = names if names else [str(i) for i in range(self.N)]
        # inverse table
        self.inv = [None]*self.N
        for i in range(self.N):
            for j in range(self.N):
                if self.mt[i][j] == self.e:
                    self.inv[i] = j; break
    def mul(self, i, j): return self.mt[i][j]
    def gens(self): return self.gen_idx
    def left_mult(self, i):
        N = self.N; M = np.zeros((N, N), dtype=np.uint8)
        for j in range(N): M[self.mt[i][j], j] = 1
        return M
    def regular_module(self):
        return {'d': self.N, 'act': [self.left_mult(i) for i in range(self.N)]}

def gen_subgroup(G, gens_idx):
    """Subgroup generated by given element indices."""
    elems = {G.e}; changed = True; gl = list(gens_idx)
    while changed:
        changed = False
        for a in list(elems):
            for g in gl:
                p = G.mt[a][g]
                if p not in elems: elems.add(p); changed = True
                p2 = G.mt[g][a]
                if p2 not in elems: elems.add(p2); changed = True
    return sorted(elems)

def double_cosets(G, Aelems, Belems):
    """Return list of (rep, coset-set) for A\\G/B."""
    seen = set(); out = []
    for g in range(G.N):
        if g in seen: continue
        cs = set()
        for a in Aelems:
            ag = G.mt[a][g]
            for b in Belems:
                cs.add(G.mt[ag][b])
        out.append((g, sorted(cs))); seen |= cs
    return out

def conj_intersection(G, Aelems, Belems, g):
    """A ∩ gBg^{-1} as element list."""
    gi = G.inv[g]
    gBg = set(G.mt[G.mt[g][b]][gi] for b in Belems)
    return sorted(set(Aelems) & gBg)

def perm_module_GmodH(G, H_elems):
    """k[G/H] as kG-module. Basis = left cosets gH; group elt i sends coset gH to (i g)H."""
    Hset = set(H_elems); seen = set(); reps = []; coset_of = {}
    for c in range(G.N):
        if c in seen: continue
        idx = len(reps); reps.append(c)
        for h in H_elems:
            e = G.mt[c][h]; coset_of[e] = idx; seen.add(e)
    d = len(reps); act = []
    for i in range(G.N):
        Mi = np.zeros((d, d), dtype=np.uint8)
        for j in range(d):
            Mi[coset_of[G.mt[i][reps[j]]], j] = 1
        act.append(Mi)
    return {'d': d, 'act': act, 'reps': reps, 'coset_of': coset_of}

# ---------------- module algebra helpers ----------------
def act_elt(G, mod, rvec):
    rvec = mod2(rvec); d = mod['d']; M = np.zeros((d, d), dtype=np.uint8)
    for i in range(G.N):
        if rvec[i]: M = (M + mod['act'][i]) & 1
    return M

def JM_subspace(G, mod):
    """J*M where J = augmentation ideal, generated as LEFT ideal by (g-1), g in gens."""
    d = mod['d']; I = np.eye(d, dtype=np.uint8); cols = []
    for g in G.gens():
        Xg = (mod['act'][g] + I) & 1
        for c in range(d): cols.append(Xg[:, c])
    if not cols: return np.zeros((d, 0), dtype=np.uint8)
    return np.array(cols, dtype=np.uint8).T

def min_generators(G, mod):
    d = mod['d']; JM = JM_subspace(G, mod)
    cur = JM.copy() if JM.shape[1] else np.zeros((d, 0), dtype=np.uint8)
    gens = []; r = rank(cur) if cur.shape[1] else 0
    for c in range(d):
        e = np.zeros((d, 1), dtype=np.uint8); e[c, 0] = 1
        cand = np.concatenate([cur, e], axis=1)
        if rank(cand) > r: cur = cand; r += 1; gens.append(e[:, 0].copy())
    return gens

# ---------------- free modules, resolution ----------------
def free_act_elt(G, m, rvec):
    blk = act_elt(G, G.regular_module(), rvec); N = G.N; d = N*m
    M = np.zeros((d, d), dtype=np.uint8)
    for t in range(m): M[N*t:N*t+N, N*t:N*t+N] = blk
    return M

def unit_vec(G, u):
    v = np.zeros(G.N, dtype=np.uint8); v[u] = 1; return v

def phi_matrix(G, gens, mod):
    N = G.N; cols = []
    for t in range(len(gens)):
        for u in range(N):
            cols.append((mod['act'][u] @ gens[t]) & 1)
    if not cols: return np.zeros((mod['d'], 0), dtype=np.uint8)
    return np.array(cols, dtype=np.uint8).T

def submodule_as_module(G, K):
    N = G.N; m = K.shape[0] // N; act = []
    for u in range(N):
        Au = free_act_elt(G, m, unit_vec(G, u)); img = (Au @ K) & 1
        X = solve(K, img); act.append(X & 1)
    return {'d': K.shape[1], 'act': act}, K

def min_resolution(G, mod, length):
    N = G.N; betti = []; boundaries = []
    gens = min_generators(G, mod); betti.append(len(gens))
    cur_mod = mod; phi = phi_matrix(G, gens, cur_mod)
    for n in range(1, length + 1):
        K = kernel(phi)
        if K.shape[1] == 0:
            betti.append(0); boundaries.append(np.zeros((phi.shape[1], 0), dtype=np.uint8))
            for _ in range(n + 1, length + 1):
                betti.append(0); boundaries.append(np.zeros((0, 0), dtype=np.uint8))
            break
        Kmod, Kincl = submodule_as_module(G, K)
        kgens_local = min_generators(G, Kmod); betti.append(len(kgens_local))
        dn_cols = [(Kincl @ g) & 1 for g in kgens_local]
        dn = (np.array(dn_cols, dtype=np.uint8).T if dn_cols
              else np.zeros((K.shape[0], 0), dtype=np.uint8))
        boundaries.append(dn); phi = phi_matrix(G, kgens_local, Kmod); cur_mod = Kmod
    return betti, boundaries

def hom_differential(G, dn, Nmod):
    Nalg = G.N; dN = Nmod['d']
    m_prev = dn.shape[0] // Nalg if dn.shape[0] else 0; m_n = dn.shape[1]
    out = np.zeros((dN * m_n, dN * m_prev), dtype=np.uint8)
    for t in range(m_n):
        col = dn[:, t]
        for i in range(m_prev):
            w = col[Nalg*i:Nalg*i+Nalg]; Aw = act_elt(G, Nmod, w)
            out[dN*t:dN*t+dN, dN*i:dN*i+dN] = Aw
    return out

def ext_tower(G, mod, Nmod, length):
    betti, boundaries = min_resolution(G, mod, length + 1)
    dN = Nmod['d']; dims = [dN * b for b in betti]; diffs = []
    for n in range(length + 1):
        if n < len(boundaries): D = hom_differential(G, boundaries[n], Nmod)
        else: D = np.zeros((dims[n+1] if n+1 < len(dims) else 0, dims[n]), dtype=np.uint8)
        diffs.append(D)
    ext = []
    for n in range(length + 1):
        Cn = dims[n]; dn = diffs[n] if n < len(diffs) else np.zeros((0, Cn), dtype=np.uint8)
        if dn.shape[1] != Cn: dn = np.zeros((dn.shape[0], Cn), dtype=np.uint8)
        ker_dim = Cn - rank(dn); im_dim = 0 if n == 0 else rank(diffs[n-1])
        ext.append(ker_dim - im_dim)
    return ext, betti

# ---------------- H^n(H;F2) for elementary abelian H ----------------
def H_elemab_dims(s, length):
    """dim H^n((Z/2)^s;F2) = C(n+s-1,s-1); s=0 -> [1,0,0,...]."""
    from math import comb
    if s == 0: return [1] + [0]*length
    return [comb(n + s - 1, s - 1) for n in range(length + 1)]

# ---------------- build D8 ----------------
def build_D8():
    # element (a,b) = r^a s^b, a in 0..3, b in 0..1; idx = 2a+b
    def idx(a, b): return 2*a + b
    def decomp(i): return (i//2, i%2)
    N = 8
    mt = [[0]*N for _ in range(N)]
    for i in range(N):
        a, b = decomp(i)
        for j in range(N):
            c, d = decomp(j)
            # (r^a s^b)(r^c s^d) = r^{a + (-1)^b c} s^{b+d}
            na = (a + (c if b == 0 else -c)) % 4
            nb = (b + d) % 2
            mt[i][j] = idx(na, nb)
    names = ['e','s','r','rs','r2','r2s','r3','r3s']
    # generators r=idx(1,0)=2, s=idx(0,1)=1
    G = FiniteGroup(mt, ident=0, gens=[2, 1], names=names)
    # named handles
    els = {'e':0,'s':1,'r':2,'rs':3,'r2':4,'r2s':5,'r3':6,'r3s':7}
    return G, els
