"""Finite groups as permutation groups on {0..n-1}; permutations are tuples perm[i]=image of i.
Composition (p*q)(i) = p(q(i))  (apply q first)."""
from itertools import product

def compose(p, q):
    return tuple(p[q[i]] for i in range(len(p)))

def identity(n):
    return tuple(range(n))

def inverse(p):
    inv = [0] * len(p)
    for i, x in enumerate(p):
        inv[x] = i
    return tuple(inv)

def closure(gens, n):
    """Generate the group from generators (list of perms). Returns sorted list of elements."""
    e = identity(n)
    elts = {e}
    frontier = [e]
    while frontier:
        new = []
        for x in frontier:
            for g in gens:
                y = compose(g, x)
                if y not in elts:
                    elts.add(y)
                    new.append(y)
        frontier = new
    return sorted(elts)

class Group:
    def __init__(self, gens, n, name=""):
        self.n = n
        self.name = name
        self.elts = closure(gens, n)
        self.order = len(self.elts)
        self.index = {g: i for i, g in enumerate(self.elts)}
        self.e = identity(n)
        # cache multiplication table indices
        self.mult = [[self.index[compose(self.elts[i], self.elts[j])]
                      for j in range(self.order)] for i in range(self.order)]
        self.inv = [self.index[inverse(self.elts[i])] for i in range(self.order)]

    def idx(self, g):
        return self.index[g]

    def subgroup_indices(self, gens):
        """Indices (in self) of the subgroup generated by gens (perms)."""
        H = closure(gens, self.n)
        return sorted(self.index[h] for h in H)

    def left_cosets(self, Hidx):
        """Left cosets gH given H as set of element-indices. Returns list of frozensets of indices."""
        Hset = set(Hidx)
        seen = set()
        cosets = []
        for gi in range(self.order):
            if gi in seen:
                continue
            coset = frozenset(self.mult[gi][hi] for hi in Hidx)
            cosets.append(coset)
            seen |= coset
        return cosets

    def double_cosets(self, Aidx, Bidx):
        """A\G/B : list of (representative_index, frozenset). Aidx,Bidx element-index lists."""
        seen = set()
        dcs = []
        for gi in range(self.order):
            if gi in seen:
                continue
            dc = set()
            for a in Aidx:
                ag = self.mult[a][gi]
                for b in Bidx:
                    dc.add(self.mult[ag][b])
            dc = frozenset(dc)
            dcs.append((gi, dc))
            seen |= dc
        return dcs

    def intersect_subgroups(self, Xidx, Yidx):
        return sorted(set(Xidx) & set(Yidx))

    def conjugate_subgroup(self, Hidx, gi):
        """g H g^{-1} as index list."""
        ginv = self.inv[gi]
        out = []
        for h in Hidx:
            out.append(self.mult[self.mult[gi][h]][ginv])
        return sorted(set(out))
