"""kG-modules over F_p and Ext via free resolutions. Uses groups.Group."""
from fp import rref, rank, nullspace, mat_vec

class Module:
    """A left kG-module: F_p vector space of dim d, with action matrices rho[gi] (d x d) for each
       group element index gi. rho[gi] @ v = gi . v."""
    def __init__(self, group, dim, rho):
        self.G = group
        self.dim = dim
        self.rho = rho  # list length G.order of (dim x dim) matrices over F_p (as list of rows)

    @staticmethod
    def trivial(group, p):
        d = 1
        rho = [[[1]] for _ in range(group.order)]
        return Module(group, 1, rho)

    @staticmethod
    def permutation_GmodH(group, Hidx, p):
        """k[G/H]: basis = left cosets gH. gi acts: coset C -> gi.C ."""
        cosets = group.left_cosets(Hidx)
        d = len(cosets)
        # map: for each coset (frozenset of elt indices), its position
        cindex = {}
        for pos, C in enumerate(cosets):
            for x in C:
                cindex[x] = pos  # element x lies in coset pos ; but we need coset-of-representative
        # coset repr: pick min element as representative label; action gi.(xH) = (gi x)H
        reps = [min(C) for C in cosets]
        rho = []
        for gi in range(group.order):
            M = [[0] * d for _ in range(d)]
            for pos in range(d):
                r = reps[pos]
                img_elt = group.mult[gi][r]
                img_pos = cindex[img_elt]
                M[img_pos][pos] = 1 % p
            rho.append(M)
        return Module(group, d, rho)

    def restrict(self, Hidx):
        """Restrict to subgroup H (element indices in G). Returns (H_as_Group_like, action list).
           We return a lightweight object with .order and rho indexed by H-position."""
        raise NotImplementedError


def free_action_on_blocks(G, r):
    """Left regular action of each group element on (kG)^r (dim r*|G|).
       basis index = i*|G| + gi  (block i, group elt gi). w acts: (i,gi) -> (i, w*gi)."""
    n = G.order
    d = r * n
    rho = []
    for wi in range(n):
        M = [[0] * d for _ in range(d)]
        for i in range(r):
            for gi in range(n):
                src = i * n + gi
                tgt = i * n + G.mult[wi][gi]
                M[tgt][src] = 1
        rho.append(M)
    return d, rho


def kG_span(G, vecs, p, ambient_rho):
    """F_p-span of kG.{vecs} inside ambient module with action ambient_rho (list of matrices).
       Returns rref basis (list of rows) of the submodule generated by vecs."""
    gens = []
    for v in vecs:
        for wi in range(G.order):
            gens.append(mat_vec(ambient_rho[wi], v, p))
    if not gens:
        return []
    R, piv = rref(gens, p)
    return [R[i] for i in range(len(piv))]


def module_generators(G, V, p):
    """Greedy kG-generating set of module V. Returns list of generator vectors (in F_p^V.dim)."""
    d = V.dim
    basis_span = []   # rref rows of current kG-span
    gens = []
    # iterate over standard basis vectors; add as generator if not in current span
    for j in range(d):
        e = [1 if k == j else 0 for k in range(d)]
        # check if e in span of basis_span
        if _in_rowspan(basis_span, e, p):
            continue
        gens.append(e)
        # extend span by kG.e
        new = kG_span_extend(G, basis_span, [e], p, V.rho)
        basis_span = new
        if len(basis_span) == d:
            break
    return gens


def _in_rowspan(rows, v, p):
    if not rows:
        return all(x % p == 0 for x in v)
    r0 = rank(rows, p)
    r1 = rank(rows + [v], p)
    return r0 == r1


def kG_span_extend(G, existing_basis, newvecs, p, rho):
    gens = [list(r) for r in existing_basis]
    for v in newvecs:
        for wi in range(G.order):
            gens.append(mat_vec(rho[wi], v, p))
    R, piv = rref(gens, p)
    return [R[i] for i in range(len(piv))]


def submodule_generators(G, subbasis_rows, ambient_rho, p):
    """Given a submodule of an ambient free module, described by an F_p basis `subbasis_rows`
       (list of vectors in ambient dim), find kG-generators (subset generating it as kG-module)."""
    target_rank = rank(subbasis_rows, p) if subbasis_rows else 0
    # work with rref of the subspace to test membership
    curr = []  # rref rows of current kG-span
    gens = []
    for v in subbasis_rows:
        if _in_rowspan(curr, v, p):
            continue
        gens.append(v)
        curr = kG_span_extend(G, curr, [v], p, ambient_rho)
        if rank(curr, p) == target_rank:
            break
    return gens


def resolve_and_ext(G, V, N, p, maxdeg):
    """Minimal-ish free resolution of V over kG; return Ext^n_{kG}(V,N) dims for n=0..maxdeg.
       Also returns list of Betti numbers (free ranks r_n)."""
    n = G.order
    # ---- Build resolution: sequence of free ranks r_k and boundary columns z (in F_{k-1} coords).
    # d_k : F_k -> F_{k-1}, columns are images of the r_k generators (vectors in F_{k-1} = (kG)^{r_{k-1}}).
    # We store for each k>=1 the list of generator-image vectors (length r_{k-1}*n).
    betti = []
    diffs = []  # diffs[k] for k>=1 : list of column vectors (images) in ambient F_{k-1}

    # Step 0: F_0 -> V
    gens0 = module_generators(G, V, p)
    r0 = len(gens0)
    betti.append(r0)
    # eps matrix: F_0 (dim r0*n) -> V (dim V.dim). column (i,gi) = rho_V(gi) @ gens0[i]
    def eps_columns():
        cols = []
        for i in range(r0):
            for gi in range(n):
                cols.append(mat_vec(V.rho[gi], gens0[i], p))
        return cols  # each is length V.dim ; column index = i*n+gi
    cols0 = eps_columns()
    # kernel of eps as subspace of F_0 : nullspace of matrix whose columns are cols0
    # matrix M0 : V.dim x (r0*n). rows = V.dim.
    def cols_to_rows(cols, height):
        # cols: list of column vectors each length height -> rows (height x len(cols))
        w = len(cols)
        return [[cols[j][i] for j in range(w)] for i in range(height)]
    M0 = cols_to_rows(cols0, V.dim)
    ker0 = nullspace(M0, p)  # vectors in F_0 dim r0*n

    prev_free_rho = None
    prev_r = r0
    cur_ker = ker0
    for k in range(1, maxdeg + 2):
        # ambient free module F_{k-1} has rank prev_r, action = block regular
        amb_dim, amb_rho = free_action_on_blocks(G, prev_r)
        gensk = submodule_generators(G, cur_ker, amb_rho, p)
        rk = len(gensk)
        betti.append(rk)
        diffs.append(gensk)  # images in F_{k-1}
        if rk == 0:
            # resolution terminated; pad
            prev_r = 0
            cur_ker = []
            # remaining diffs empty
            for kk in range(k + 1, maxdeg + 2):
                betti.append(0)
                diffs.append([])
            break
        # compute ker of d_k : F_k -> F_{k-1}
        # d_k columns: for generator j, for group elt wi: amb_rho[wi] @ gensk[j]  (vector in F_{k-1})
        cols = []
        for j in range(rk):
            for wi in range(n):
                cols.append(mat_vec(amb_rho[wi], gensk[j], p))
        # matrix M_k : amb_dim x (rk*n)
        Mk = cols_to_rows(cols, amb_dim)
        cur_ker = nullspace(Mk, p)  # in F_k dim rk*n
        prev_r = rk

    # ---- Apply Hom(-,N): compute Ext dims.
    # Hom(F_k,N) has dim betti[k]*N.dim. differential d_{k+1}^* : Hom(F_k,N) -> Hom(F_{k+1},N)
    # given by: for phi determined by w_0..w_{r_k-1} in N, (d^* phi)(gen_j of F_{k+1})
    #   = phi(diffs[k+1][j])  where diffs[k+1][j] in F_k = (kG)^{r_k}.
    # diffs[k+1][j] as vector length r_k * n : coeff at (i,gi). phi(basis(i,gi)) = rho_N(gi) w_i.
    def dstar_matrix(k):
        """matrix of d_{k+1}^*: (N.dim*r_k) -> (N.dim*r_{k+1}).  Uses diffs[k] which is diffs list
           index = (k+1)-1 = k (diffs[0] is d_1)."""
        rk = betti[k]
        rk1 = betti[k + 1]
        Nd = N.dim
        if rk1 == 0 or rk == 0:
            return [], rk * Nd, rk1 * Nd
        # unknown vector in domain = concat over i in 0..rk-1 of w_i (each Nd). index dom = i*Nd + a
        # output = concat over j in 0..rk1-1 of phi(diffs_j) (each Nd). index out = j*Nd + b
        dom = rk * Nd
        out = rk1 * Nd
        M = [[0] * dom for _ in range(out)]
        cols_of_diff = diffs[k]  # list length rk1 ; each vector length rk*n
        for j in range(rk1):
            zj = cols_of_diff[j]
            # zj coeff at index i*n+gi
            for i in range(rk):
                for gi in range(n):
                    c = zj[i * n + gi] % p
                    if c == 0:
                        continue
                    rn = N.rho[gi]  # Nd x Nd
                    # contribution: c * rho_N(gi) applied to w_i -> adds to output block j
                    for b in range(Nd):
                        row = j * Nd + b
                        for a in range(Nd):
                            M[row][a + i * Nd] = (M[row][a + i * Nd] + c * rn[b][a]) % p
        return M, dom, out

    # ranks of d^* maps
    dims = []
    rank_prev = 0  # rank of d_k^* : Hom(F_{k-1},N)->Hom(F_k,N), for k=0 nothing
    ranks = {}
    for k in range(0, maxdeg + 1):
        M, dom, out = dstar_matrix(k)
        rk_dstar = rank(M, p) if M else 0
        ranks[k] = (rk_dstar, dom, out)
    for k in range(0, maxdeg + 1):
        dom_dim = betti[k] * N.dim
        rank_out = ranks[k][0]  # rank of d_{k+1}^* leaving degree k
        rank_in = ranks[k - 1][0] if k - 1 >= 0 else 0  # rank of d_k^* arriving at degree k
        ext = dom_dim - rank_out - rank_in
        dims.append(ext)
    return dims, betti
