"""
Search for a finite category K and a WIDE subcategory D (closed under comp,
contains all identities, AND contains at least one cross-object arrow) such that:

  (L) every right D-module Hom_K(-,b) is FREE, but
  (G) no choice of free bases forms a wide subcategory C
      => criterion(K,Dset) == (False, True, None)
      => brute-force: NO wide C gives an SFS with D.

This is the "genuinely pairwise" holonomy obstruction: D must carry a Z/2 loop
(to create holonomy) AND a cross arrow.
"""

from pairwise_zs_check import FinCat
from pairwise_end_to_end import (
    wide_subcats, is_sfs, Dmodule_is_free, criterion, full_check,
)


def validate(K, Dset, label, want_cross=True):
    print("=" * 70)
    print("CANDIDATE:", label)
    cat = K.check_category(verbose=True)
    print("  check_category:", cat)
    if not cat:
        print("  -> NOT a category, abort")
        return False
    # D contains identities?
    ids = set(K.ident[o] for o in K.objects)
    print("  D contains all identities:", ids <= Dset)
    # D closed under comp?
    closed = True
    for g in Dset:
        for f in Dset:
            if K.cod(f) == K.dom(g) and K.compose(g, f) not in Dset:
                closed = False
                print("  D not closed:", g, "o", f, "=", K.compose(g, f))
    print("  D closed under comp:", closed)
    # cross arrow?
    cross = [d for d in Dset if K.dom(d) != K.cod(d)]
    print("  D cross-object arrows:", cross)
    if want_cross and not cross:
        print("  -> D has no cross arrow")
    # free modules
    allfree = True
    for b in K.objects:
        bs = Dmodule_is_free(K, Dset, b)
        print(f"  Hom(-,{b}) free bases:", [sorted(x) for x in bs])
        if not bs:
            allfree = False
    print("  (L) all D-modules free:", allfree)
    # criterion
    crit, L, C = criterion(K, Dset, verbose=True)
    print("  criterion (crit,L,C):", crit, L, sorted(C) if C else C)
    # brute force ground truth
    truth = any(is_sfs(K, Cc, Dset) for Cc in wide_subcats(K))
    print("  brute-force SFS-exists:", truth)
    success = (cat and (ids <= Dset) and closed and allfree
               and crit is False and L is True and C is None
               and truth is False and (cross if want_cross else True))
    print("  *** SUCCESS:", bool(success), "***")
    return bool(success)


# ---------------------------------------------------------------------------
# ATTEMPT 1.
# Objects a, x, y.
# D should carry the Z/2 loop g at a AND a cross arrow.  Idea: REVERSE the
# rigid twist so that the branch a -> x => y has its *group* living downstream.
#
# We instead build: D = subcategory generated by g:a->a (g^2=1a) and a cross
# arrow d:a->x.  Closure forces d and dg=d o g.  Put a SINGLE C-cross arrow
# c:x->y but a Z/2 worth of arrows a->y giving holonomy.
#
# Let's just hand-build a category and test.  We mirror rigid_twist but move
# the loop into D and keep an obstruction on the C-side at the top object.
# ---------------------------------------------------------------------------

def attempt1():
    """
    Objects a,x,y.
    End(a) = Z/2 = {1a, g}.
    Hom(a,x) = {d, dg}     (d:a->x, dg = d o g)        -- want these in D
    Hom(x,y) = {c, c2}     (two arrows x->y)            -- C side, x has trivial End
    Hom(a,y) = {e, eg}     (e = c o d, etc)
    D = {1a, g, 1x, 1y, d, dg}.   (loop g + cross arrow d, plus identities)
    We must define c o d, c2 o d, c o dg, c2 o dg with a TWIST so no consistent
    C-transversal closes.
    """
    objs = ["a", "x", "y"]
    arrows = {
        "1a": ("a", "a"), "g": ("a", "a"),
        "1x": ("x", "x"), "1y": ("y", "y"),
        "d": ("a", "x"), "dg": ("a", "x"),
        "c": ("x", "y"), "c2": ("x", "y"),
        "e": ("a", "y"), "eg": ("a", "y"),
    }
    comp = {}
    # End(a)=Z2
    comp[("1a","1a")]="1a"; comp[("1a","g")]="g"; comp[("g","1a")]="g"; comp[("g","g")]="1a"
    comp[("1x","1x")]="1x"; comp[("1y","1y")]="1y"
    idof={"a":"1a","x":"1x","y":"1y"}
    for f,(dm,cd) in arrows.items():
        comp[(f, idof[dm])]=f
        comp[(idof[cd], f)]=f
    # right action of g on Hom(a,x): d o g = dg, dg o g = d
    comp[("d","g")]="dg"; comp[("dg","g")]="d"
    # right action of g on Hom(a,y): e o g = eg, eg o g = e
    comp[("e","g")]="eg"; comp[("eg","g")]="e"
    # cross composites x->y after a->x.  TWIST (same shape as rigid twist):
    #   c o d = e,  c2 o d = eg,  c o dg = eg,  c2 o dg = e
    comp[("c","d")]="e";  comp[("c2","d")]="eg"
    comp[("c","dg")]="eg"; comp[("c2","dg")]="e"
    ident={"a":"1a","x":"1x","y":"1y"}
    return FinCat(objs, arrows, comp, ident)


if __name__ == "__main__":
    K = attempt1()
    validate(K, {"1a","g","1x","1y","d","dg"}, "attempt1: D={1a,g,1x,1y,d,dg}")
