"""
Plethysm Lemma — stabilizer-invariant computation.

Setting (species / analytic functors over Set):
  A species A is given by its MOLECULAR decomposition: a list of constituents
  (n, H) where H <= S_n is a subgroup; constituent = X^n / H  (functions [n]->X
  mod H permuting arguments).  A[n] contains the transitive orbit S_n/H.
  Analytic functor:  ~A(X) = coprod_constituents  X^n / H.
  A is FLAT  <=>  every H is trivial  <=>  ~A is polynomial.

Composition of analytic functors = plethysm of species:  ~A o ~B = ~(A . B).
So we realize A.A as  ~A(~A(X)),  iterating the evaluation.

Invariant (Lemma E):  a natural iso F ~= G of Set-endofunctors restricts, at
each finite X, to an Aut(X)=S_X-equivariant bijection, so
    S_X(F) := { Stab_{FX}(x) <= S_X : x in FX }   (as ACTUAL subgroups)
is preserved EXACTLY:  S_X(F) = S_X(G).

Key reduction:  if R is FLAT then ~R(Y) = coprod_i Y^{m_i} (labeled products),
so every stabilizer of R.A on X is an INTERSECTION of stabilizers of ~A on X:
    S_X(R.A) subseteq  IntersectionClosure( S_X(~A) ).
Hence: if some element of A.A on some X has a stabilizer NOT in the intersection
closure of S_X(~A), then A.A !~= R.A for EVERY flat R.  That refutes (star) for A.
"""

from itertools import permutations, product
from functools import reduce

# ---------- permutations as tuples over range(k); compose p*q : i |-> p[q[i]] ----------
def idperm(k): return tuple(range(k))
def compose(p, q): return tuple(p[q[i]] for i in range(len(q)))
def inverse(p):
    inv = [0]*len(p)
    for i,x in enumerate(p): inv[x]=i
    return tuple(inv)

def close_group(gens, k):
    """subgroup of S_k generated by gens (tuples), returned as frozenset of tuples."""
    G = {idperm(k)}
    frontier = [idperm(k)]
    gens = list(gens) + [inverse(g) for g in gens]
    while frontier:
        x = frontier.pop()
        for g in gens:
            y = compose(g, x)
            if y not in G:
                G.add(y); frontier.append(y)
    return frozenset(G)

def sym_group(k):
    return frozenset(permutations(range(k)))

# ---------- species evaluation ----------
class Species:
    def __init__(self, constituents):
        # constituents: list of (n, gens) ; gens list of tuples in S_n
        self.constituents = []
        for (n, gens) in constituents:
            H = close_group(gens, n)
            self.constituents.append((n, H))
    def is_flat(self):
        return all(len(H)==1 for (n,H) in self.constituents)

def canon(tup, H):
    """canonical (min) representative of the H-orbit of function tup:[n]->base,
       H permuting positions:  (h . f)[i] = f(h[i])."""
    return min(tuple(tup[h[i]] for i in range(len(tup))) for h in H)

def evaluate(A, base):
    """Evaluate ~A at a base set given as a list of hashable elements.
       Returns (elements, act) where
         elements = list of ('c', cidx, canon_tuple)   (global element list)
         act(tau_on_base_as_dict) -> permutation (list) on element indices.
       tau_on_base is a dict mapping base element -> base element."""
    elements = []
    index = {}
    per_const = []  # (cidx, n, H)
    for cidx,(n,H) in enumerate(A.constituents):
        seen = set()
        for f in product(base, repeat=n):
            c = canon(f, H)
            if c not in seen:
                seen.add(c)
                el = ('c', cidx, c)
                index[el] = len(elements)
                elements.append(el)
        per_const.append((cidx,n,H))
    def act(tau):
        # tau: dict base->base
        perm = [None]*len(elements)
        for idx, el in enumerate(elements):
            _, cidx, tup = el
            n = A.constituents[cidx][0]; H = A.constituents[cidx][1]
            newf = tuple(tau[tup[i]] for i in range(n))
            c = canon(newf, H)
            perm[idx] = index[('c', cidx, c)]
        return perm
    return elements, act

def base_perm_dict(perm_tuple, base):
    """turn a permutation tuple on range(len(base)) into dict base->base when base=range."""
    return {i: perm_tuple[i] for i in range(len(base))}

# ---------- stabilizer machinery ----------
def stabilizers_on_X(A, x_size):
    """S_X(~A): for X = range(x_size), compute set of stabilizer subgroups (frozensets of tuples)."""
    base = list(range(x_size))
    elements, act = evaluate(A, base)
    Sx = list(permutations(range(x_size)))
    # induced perm on elements for each tau
    induced = {}
    for tau in Sx:
        induced[tau] = act({i:tau[i] for i in range(x_size)})
    stabs = set()
    stab_of = []  # per element
    for idx in range(len(elements)):
        S = frozenset(tau for tau in Sx if induced[tau][idx]==idx)
        stabs.add(S)
        stab_of.append(S)
    return stabs, elements, stab_of

def evaluate_composite(A, x_size):
    """Realize A.A = ~A(~A(X)) at X=range(x_size); return (Zelements, stab_of_Z as frozensets in S_X)."""
    base = list(range(x_size))
    Yelements, Yact = evaluate(A, base)              # Y = ~A(X)
    Ybase = list(range(len(Yelements)))              # relabel Y as 0..|Y|-1
    Zelements, Zact = evaluate(A, Ybase)             # Z = ~A(Y)
    Sx = list(permutations(range(x_size)))
    stabs = set()
    stab_of = []
    # induced action of tau in S_X on Y, then on Z
    for idx in range(len(Zelements)):
        stab_of.append(None)
    z_stab = [set() for _ in range(len(Zelements))]
    Zinduced = {}
    for tau in Sx:
        yperm = Yact({i:tau[i] for i in range(x_size)})   # perm on Y indices
        zperm = Zact({j:yperm[j] for j in range(len(Yelements))})
        Zinduced[tau] = zperm
    for idx in range(len(Zelements)):
        S = frozenset(tau for tau in Sx if Zinduced[tau][idx]==idx)
        stabs.add(S)
        stab_of[idx]=S
    return stabs, Zelements, stab_of

def intersection_closure(subgroups, x_size):
    """closure of a set of subgroups (frozensets of tuples in S_x) under intersection,
       including the full group S_x (empty intersection)."""
    full = sym_group(x_size)
    closure = set(subgroups)
    closure.add(full)
    changed = True
    while changed:
        changed = False
        cur = list(closure)
        for i in range(len(cur)):
            for j in range(i, len(cur)):
                inter = cur[i] & cur[j]
                if inter not in closure:
                    closure.add(inter); changed = True
    return closure

# ---------- labeling helpers ----------
def young_subgroups(x_size):
    """all Young (set-partition) subgroups of S_x: product of Sym(block) over a set partition."""
    from itertools import chain
    base = list(range(x_size))
    def partitions(s):
        if not s:
            yield []
            return
        first = s[0]
        rest = s[1:]
        for smaller in partitions(rest):
            # add first to an existing block or its own
            for i in range(len(smaller)):
                yield smaller[:i] + [ [first]+smaller[i] ] + smaller[i+1:]
            yield [[first]] + smaller
    res = {}
    for part in partitions(base):
        gens = []
        for block in part:
            for a in range(len(block)-1):
                # transposition (block[a] block[a+1])
                t = list(range(x_size))
                t[block[a]], t[block[a+1]] = t[block[a+1]], t[block[a]]
                gens.append(tuple(t))
        G = close_group(gens, x_size)
        res[frozenset(tuple(sorted(b)) for b in part)] = G
    return res

def describe_group(G, x_size):
    order = len(G)
    Ys = young_subgroups(x_size)
    is_young = any(G==Y for Y in Ys.values())
    return f"order={order}, young={is_young}"
