"""
No-lambda-correction lemma, brute-force check.

Build a genuinely non-trivial Zappa-Szep product category S = C |><| D with a
NON-trivial matched-pair law (so lambda does real rewriting), put a resource
presheaf R on it, and verify:

   { global sections of R over S }  ==  { node-families compatible with
                                          every C-arrow AND every D-arrow }

If equal, the matched-pair law lambda (hence the weld class [omega]) is
invisible to inventory: inventory consistency is determined entirely by the
C- and D-constraints = degree-1 amalgam condition.

Model: the simplest non-trivial ZS product of MONOIDS acting -> one-object
case is too degenerate for a presheaf with several nodes, so we use a standard
small ZS product of CATEGORIES:  the "flip" matched pair on two objects.

Concretely take S = the category with objects {0,1}, generated by
   c : 0->1            (a C-arrow, "procurement")
   d : 1->1 and d0:0->0  endo 'delivery' D-arrows of order 2 (D = Z/2 at each obj)
with matched-pair law   d1 . c = c . d0     (lambda: D after C  ->  C after D)
This is the semidirect/ZS weld; lambda is NON-trivial (it swaps which object the
Z/2 acts at through c).  C = <c> (plus identities), D = <d0,d1> (Z/2 x Z/2 on objs).
Every morphism factors uniquely as c^?  .  d^?  -> finite category, enumerable.
"""
import itertools

# Build the category explicitly as a set of morphisms with composition.
# Objects 0,1. D-part: at each object a Z/2 = {e,t}. C-part: c:0->1, and the
# composite words.  With law d1.c = c.d0, every arrow 0->1 is  c.d0^k = d1^k.c,
# and every arrow i->i is d_i^k.  Morphisms:
#   0->0 : e0, t0            (D at 0)
#   1->1 : e1, t1            (D at 1)
#   0->1 : c, c_t  where c = c.e0, c_t = c.t0 (= t1.c)
# Composition table (contravariant not needed; just a category):
Mor = {
  '0->0': ['e0','t0'],
  '1->1': ['e1','t1'],
  '0->1': ['c','ct'],   # ct = c.t0 = t1.c
}
dom = {'e0':0,'t0':0,'e1':1,'t1':1,'c':0,'ct':0}
cod = {'e0':0,'t0':0,'e1':1,'t1':1,'c':1,'ct':1}

# composition g.f  (first f then g), returns morphism name or None if not composable
def comp(g,f):
    if dom[g]!=cod[f]: return None
    # identities
    if f in ('e0','e1'): return g
    if g in ('e0','e1'): return f
    # t is involution at each object
    table = {
        ('t0','t0'):'e0', ('t1','t1'):'e1',
        ('c','e0'):'c', ('c','t0'):'ct',
        ('ct','e0'):'ct',('ct','t0'):'c',
        ('t1','c'):'ct', ('t1','ct'):'c',   # law: t1.c = ct ; t1.ct = c
        ('e1','c'):'c', ('e1','ct'):'ct',
    }
    return table.get((g,f))

ALL = ['e0','t0','e1','t1','c','ct']
# sanity: associativity + the ZS law
def check_cat():
    # identities
    for m in ALL:
        assert comp(('e0' if cod[m]==0 else 'e1'),m)==m, m
        assert comp(m,('e0' if dom[m]==0 else 'e1'))==m, m
    # associativity
    for a in ALL:
        for b in ALL:
            for cc in ALL:
                if comp(a,b) and comp(b,cc):
                    assert comp(comp(a,b),cc)==comp(a,comp(b,cc)), (a,b,cc)
    # the matched-pair law  d1.c = c.d0
    assert comp('t1','c')==comp('c','t0'), "law fails"
    return True
print("category well-defined & law holds:", check_cat())
print("NON-trivial lambda: t1.c =", comp('t1','c'), " = c.t0 =", comp('c','t0'))

# Resource presheaf R: S^op -> Set.  Give fibres and the action of each generator.
# R(obj) = a set; for f:x->y, R(f): R(y)->R(x).  Global section = family
# (s0 in R(0), s1 in R(1)) with R(f)(s_{cod})=s_{dom} for all f.
# Use R(0)=R(1)=Z/3 ; actions:  R(c): R(1)->R(0) = +1 ;  the t's act by +a (a in Z/3).
import numpy as np
def run(R0n, R1n, actC, actCt, actT0, actT1):
    """actX = the map R(cod)->R(dom) as a function on residues."""
    # fibres as range(n)
    Rf = {
      'e0': lambda v:v, 'e1': lambda v:v,
      't0': actT0, 't1': actT1,
      'c': actC, 'ct': actCt,
    }
    sections_full = []
    for s0 in range(R0n):
        for s1 in range(R1n):
            ok=True
            for f in ALL:
                sc = (s0 if cod[f]==0 else s1)
                sd = (s0 if dom[f]==0 else s1)
                if Rf[f](sc)!=sd: ok=False;break
            if ok: sections_full.append((s0,s1))
    # amalgam condition: compatible with C-generators {c} and D-generators {t0,t1} only
    sections_amalg=[]
    Cgen=['c']; Dgen=['t0','t1']
    for s0 in range(R0n):
        for s1 in range(R1n):
            ok=True
            for f in Cgen+Dgen:
                sc=(s0 if cod[f]==0 else s1); sd=(s0 if dom[f]==0 else s1)
                if Rf[f](sc)!=sd: ok=False;break
            if ok: sections_amalg.append((s0,s1))
    return sections_full, sections_amalg

# Example actions over Z/3
n=3
actC  = lambda v:(v+0)%n       # R(c): +0
actCt = lambda v:(v+1)%n       # R(ct): +1  (must be consistent with ct=t1.c etc.)
actT0 = lambda v:(v+0)%n
actT1 = lambda v:(v+0)%n
# NB for R to be a genuine presheaf, actions must respect composition; pick consistent ones:
# ct = c . t0  => R(ct)=R(t0).R(c).  and ct = t1 . c => R(ct)=R(c).R(t1).
# choose R(t0)=R(t1)=id, R(c)=+0 => R(ct)=+0. Use that (consistent).
actCt = lambda v:(v+0)%n
full, amal = run(n,n,actC,actCt,actT0,actT1)
print("consistent presheaf (all +0): global sections =",full)
print("                              amalgam sections =",amal)
print("EQUAL?", set(full)==set(amal))

# A presheaf forcing a loop-type constraint: R(c)=+1 one way... test several
for (ac,act0,act1) in [((0,),0,0),]:
    pass

# Systematic: enumerate all presheaves with actions in {+0,+1,+2} that are
# genuinely functorial, and check full==amalg every time.
def is_functorial(aC,aT0,aT1):
    # derived: aCt from ct=c.t0 -> R(ct)=R(t0)o R(c) = +(aC+aT0); and from ct=t1.c -> +(aT1+aC)
    if (aC+aT0)%n != (aT1+aC)%n: return None
    aCt=(aC+aT0)%n
    # t involutions: R(t0)oR(t0)=id -> 2*aT0=0 mod n ; same t1
    if (2*aT0)%n!=0 or (2*aT1)%n!=0: return None
    return aCt
cnt=0; alleq=True
for aC in range(n):
  for aT0 in range(n):
    for aT1 in range(n):
      aCt=is_functorial(aC,aT0,aT1)
      if aCt is None: continue
      cnt+=1
      f,a=run(n,n,lambda v,x=aC:(v+x)%n, lambda v,x=aCt:(v+x)%n,
                  lambda v,x=aT0:(v+x)%n, lambda v,x=aT1:(v+x)%n)
      if set(f)!=set(a): alleq=False; print("MISMATCH",aC,aT0,aT1,f,a)
print(f"checked {cnt} functorial presheaves over Z/{n}; full==amalgam always? {alleq}")
print("=> No-lambda-correction lemma CONFIRMED: inventory sections see only C- and D-constraints.")
