"""
Independent computation of H^1(U;k) as crossed homomorphisms / im(principal),
for trivial coefficient module k. With trivial action:
  Z^1 = Hom_{grp}(U, (k,+)),   B^1 = 0,   so H^1 = Hom(U,(k,+)).
We enumerate ALL functions f:U->k, impose the cocycle condition
  f(uv) = f(u) + u.f(v) = f(u) + f(v)   (trivial action),
and count the solution space dimension over the field. This is a brute,
assumption-free check that does NOT use the periodic resolution.
Also emits the explicit generator for the S3 witness (U=C2 over F2).
"""

def compose(p, q):
    return tuple(p[q[i]] for i in range(len(p)))

def identity(n):
    return tuple(range(n))

def closure(gens, n):
    e = identity(n); elems={e}; fr=[e]
    while fr:
        x=fr.pop()
        for g in gens:
            y=compose(g,x)
            if y not in elems: elems.add(y); fr.append(y)
    return elems

def stab(group, s):
    return {g for g in group if g[s]==s}

def h1_trivial_dim(U, char):
    """dim over field of Z^1=Hom(U,(k,+)); B^1=0 for trivial action.
       Build linear system over the field: unknowns f(u) for u in U,
       equations f(uv)-f(u)-f(v)=0, plus f(e)=0."""
    Ul = sorted(U)
    idx = {u:i for i,u in enumerate(Ul)}
    m = len(Ul)
    e = identity(len(Ul[0]))
    rows = []
    # f(e)=0
    r=[0]*m; r[idx[e]]=1; rows.append(r)
    for u in Ul:
        for v in Ul:
            uv = compose(u,v)
            r=[0]*m
            r[idx[uv]] += 1
            r[idx[u]]  -= 1
            r[idx[v]]  -= 1
            rows.append(r)
    rank = _rank(rows, char, m)
    return m - rank

def _rank(rows, p, cols):
    if p==0:
        from sympy import Matrix
        return Matrix(rows).rank()
    A=[[x % p for x in row] for row in rows]
    r=0
    for c in range(cols):
        piv=None
        for i in range(r,len(A)):
            if A[i][c]%p!=0: piv=i;break
        if piv is None: continue
        A[r],A[piv]=A[piv],A[r]
        inv=pow(A[r][c],p-2,p)
        A[r]=[(x*inv)%p for x in A[r]]
        for i in range(len(A)):
            if i!=r and A[i][c]%p!=0:
                f=A[i][c]; A[i]=[(A[i][k]-f*A[r][k])%p for k in range(cols)]
        r+=1
        if r==len(A):break
    return r

if __name__=="__main__":
    c3=(1,2,0); t12=(1,0,2)
    S3=closure([c3,t12],3); U_s3=stab(S3,0)
    v_a=(1,0,3,2); v_b=(2,3,0,1); c123=(1,2,0,3)
    A4=closure([v_a,v_b,c123],4); U_a4=stab(A4,0)

    print("Brute crossed-hom H^1 dims (independent of resolution):")
    print(f"{'U':>10} | char0 char2 char3")
    for name,U in [("C2 (S3)",U_s3),("C3 (A4)",U_a4)]:
        dims=[h1_trivial_dim(U,ch) for ch in (0,2,3)]
        print(f"{name:>10} |   {dims[0]}     {dims[1]}     {dims[2]}")

    print("\n--- Explicit generator of H^1(C2;F2) for S3 witness ---")
    Ul=sorted(U_s3); e=identity(3)
    nontriv=[u for u in Ul if u!=e][0]
    print(f"U = {{ e={e}, r={nontriv} }}  (r is the transposition (23), order 2)")
    print("Nontrivial crossed hom f: U -> F2 (trivial action), f(e)=0, f(r)=1.")
    print("Cocycle check f(xy)=f(x)+f(y) over F2:")
    fmap={e:0, nontriv:1}
    ok=True
    for x in Ul:
        for y in Ul:
            lhs=fmap[compose(x,y)]; rhs=(fmap[x]+fmap[y])%2
            ok = ok and (lhs==rhs)
    print(f"  all products satisfy 1-cocycle identity: {ok}")
    print("  f is NOT a coboundary (B^1=0 for trivial action) => nonzero in H^1.")
    print("  => H^1(C2;F2)=F2, generated by u |-> (u != e).")
